"""empty message

Revision ID: 644589359c2b
Revises: be3e418a7508
Create Date: 2021-01-24 18:59:04.901831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644589359c2b'
down_revision = 'be3e418a7508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
